#creator Fardeen Bholai
#pipeline blijvenleren

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastructuur

pool:
  vmImage: ubuntu-latest

variables:
 resourcegroupname: 'blijvenleren'

steps:
- task: AzureCLI@2
  displayName: preview bicep changes
  inputs:
    azureSubscription: 'IBIS AVD TEST'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group what-if --name 'preview changes+$(Build.BuildNumber)' --resource-group $(resourcegroupname) --template-file ./infrastructuur/main.bicep --parameters ./infrastructuur/main.parameters.json  

- task: AzureCLI@2
  displayName: deploy bicep to azure
  inputs:
    azureSubscription: 'IBIS AVD TEST'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --name $(Build.BuildNumber) --resource-group $(resourcegroupname) --template-file ./infrastructuur/main.bicep --parameters ./infrastructuur/main.parameters.json  

